---
kind: Template
apiVersion: v1
metadata:
  name: rdsi-server
objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: "rdsi-server:${TAG}"
      source:
        contextDir: server
        git:
          ref: feature/create-projects
          uri: "https://github.com/bcgov/citz-dst-capstone-2021"
        type: Git
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: "nodejs:12-ubi8"
            namespace: openshift
        type: Source
      triggers:
        - type: ConfigChange
        - type: ImageChange
    metadata:
      labels:
        build: rdsi-server
      name: rdsi-server
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    spec:
      lookupPolicy:
        local: false
    metadata:
      generation: 1
      labels:
        build: rdsi-server
      name: rdsi-server
parameters:
  - name: TAG
    required: true
    description: version as an image tag
