kind: Template
apiVersion: v1
objects:
  - apiVersion: v1
    kind: Service
    spec:
      ports:
        - name: ${PORT}-tcp
          port: ${{PORT}}
          protocol: TCP
          targetPort: ${{PORT}}
      selector:
        deployment: rdsi-app
      sessionAffinity: None
      type: ClusterIP
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        app: rdsi-app
        app.kubernetes.io/component: rdsi-app
        app.kubernetes.io/instance: rdsi-app
      name: rdsi-app
  - apiVersion: apps/v1
    kind: Deployment
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          deployment: rdsi-app
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
          creationTimestamp: null
          labels:
            deployment: rdsi-app
            app: rdsi-app
        spec:
          containers:
            - image: >-
                image-registry.openshift-image-registry.svc:5000/adccd1-tools/rdsi-app@sha256:09da2303a817ed2e2e77b097a261135ea557592170d3d970412ea0b6c9d0cbfc
              imagePullPolicy: IfNotPresent
              name: rdsi-app
              ports:
                - containerPort: ${{PORT}}
                  protocol: TCP
              env:
                - name: PORT
                  value: ${PORT}
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
    metadata:
      annotations:
        deployment.kubernetes.io/revision: "2"
        image.openshift.io/triggers: >-
          [{"from":{"kind":"ImageStreamTag","name":"rdsi-app:0.1.0","namespace":"adccd1-tools"},"fieldPath":"spec.template.spec.containers[?(@.name==\"rdsi-app\")].image"}]
        openshift.io/generated-by: OpenShiftNewApp
      generation: 2
      labels:
        app: rdsi-app
        app.kubernetes.io/component: rdsi-app
        app.kubernetes.io/instance: rdsi-app
      name: rdsi-app
parameters:
  - name: PORT
    required: true
    description: service open port
